### ISSUE TITLE
add pydocstyle checks and fix the findings

### ISSUE THREAD

**Issue by weakcamel** [speechmatics/speechmatics-python#11]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
As a developer, I want the source code checked against `pydocstyle` checker when i type `make lint`.

I also want the CI to pass only when docstrings comply with the checker's verdict.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by TudorCRL** [comment]
Closed because this issue is very old
