### ISSUE TITLE
No support for https endpoints?

### ISSUE THREAD

**Issue by johann-petrak** [speechmatics/speechmatics-python#48]
I wanted to try out the API as documented here: https://docs.speechmatics.com/en/cloud/howto/
and was searching for a Python library to use instead of the ugly curl commands and found this package, 
but apparently it only supports websockets not https endpoints? 

`websockets.exceptions.InvalidURI: https://trial.asr.api.speechmatics.com isn't a valid URI: scheme isn't ws or wss`

If I have a https URL that works with https://docs.speechmatics.com/en/cloud/howto/, is it possible to find a corresponding websocket url that works with this library?

When I use `--url ws://trial.asr.api.speechmatics.com/v2` is still get the error message complaining about https://...

**Comment by paulg-speechmatics** [comment]
Hi @johann-petrak, we're currently in the process of updating our Python client library to support both real-time and batch API operations - we'll let you know when this has been done!

**Comment by johann-petrak** [comment]
Thanks - I have in the meantime implemented my own code for this, but it will sure help future users.

**Comment by giorgosHadji** [comment]
This should solve your issue @johann-petrak . [batch-client](https://github.com/speechmatics/speechmatics-python#batch-asr)
