### ISSUE TITLE
transcribe remote resource

### ISSUE THREAD

**Issue by drzraf** [speechmatics/speechmatics-python#54]
**Is your feature request related to a problem? Please describe.**
The cli (and the API) should support transcribe remote (publicly available) resources (like assemblyai.com).

**Describe the solution you'd like**
Allow passing an URL as a FILEPATH to `speechmatics batch transcribe`

**Additional context**
Uploading from a machine may be very slow while fetching from a server/bucket/remote resource is fast and cheap.

**Comment by TudorCRL** [comment]
Hi there!

Thanks for reaching out to us, it's always good to get feedback on the product.

Speechmatics already supports transcribing publicly available resources as you've requested. You can find the docs here at https://docs.speechmatics.com/features-other/fetch-url. We're also planning to add support for this to the CLI/SDK soon!

**Comment by TudorCRL** [comment]
Sorry that there's not been any progress (to anyone who may return to this thread). Thought it would be worth sharing a similar question that was asked in [stackoverflow](https://stackoverflow.com/questions/75872125/speechmatics-submit-a-job-without-audio-argument/76124108#76124108), where there is a temporary solution provided while we get the fix in.

**Comment by TudorCRL** [comment]
Just an update, this feature has been added to the SDK now, a code example can be found in the stackoverflow question linked above

**Comment by erkkimon** [comment]
Should fetch_data work with JavaScript SDK as well, or only Python?

**Comment by nickgerig** [comment]
@erkkimon I've documented the issue and workaround here: https://github.com/speechmatics/speechmatics-js-sdk/issues/49
